name: zip folder

on:
  push:
    paths:
      - 'published_stories/static/**'
      - '!published_stories/static/temp/**'
      - '!published_stories/static/static.zip'

permissions:
  contents: write

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out...
        uses: actions/checkout@v2
        
      - name: create new zip
        uses: vimtor/action-zip@v1
        with:
          files: published_stories/static/
          dest: published_stories/static/static.zip

      - name: commit and push report
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.MELODY_TOKEN }}
          branch: main
          force: true
          message: 'static zip update'